FROM microsoft/dotnet:2.1-sdk-alpine AS build-env
# Set the working directory witin the container
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "eventapp.dll"]
ENV ASPNETCORE_URLS http://+:5000

