version: '3'
services:
  mysql:
    container_name: eventapp_mysql
    build: 
      context: ./docker/db/
      dockerfile: ./dockerfile
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_USER: eventapp
      MYSQL_PASSWORD: password
   
